import { countryName } from '@/lib/analytics-places'

/**
 * A COUNTRY'S NAME FROM GOOGLE'S CODE. Search Console names countries by ISO 3166-1 alpha-3
 * ("USA", "NLD"); the browser's Intl.DisplayNames (analytics-places.ts `countryName`) knows only
 * alpha-2. So: alpha-3 → alpha-2 here, then the same name the Analytics page shows.
 *
 * The table is GENERATED from i18n-iso-countries (a dev dependency, so not shipped): each entry
 * is the alpha-3 code then its alpha-2. tests/unit/manager-tools/seo/search-model.test.ts checks
 * it against the package, so a hand edit or a stale copy fails there.
 */
export const A3_TO_A2_TABLE = [
  'ANDAD AREAE AFGAF ATGAG AIAAI ALBAL ARMAM AGOAO ATAAQ ARGAR ASMAS AUTAT AUSAU ABWAW ALAAX AZEAZ',
  'BIHBA BRBBB BGDBD BELBE BFABF BGRBG BHRBH BDIBI BENBJ BLMBL BMUBM BRNBN BOLBO BESBQ BRABR BHSBS',
  'BTNBT BVTBV BWABW BLRBY BLZBZ CANCA CCKCC CODCD CAFCF COGCG CHECH CIVCI COKCK CHLCL CMRCM CHNCN',
  'COLCO CRICR CUBCU CPVCV CUWCW CXRCX CYPCY CZECZ DEUDE DJIDJ DNKDK DMADM DOMDO DZADZ ECUEC ESTEE',
  'EGYEG ESHEH ERIER ESPES ETHET FINFI FJIFJ FLKFK FSMFM FROFO FRAFR GABGA GBRGB GRDGD GEOGE GUFGF',
  'GGYGG GHAGH GIBGI GRLGL GMBGM GINGN GLPGP GNQGQ GRCGR SGSGS GTMGT GUMGU GNBGW GUYGY HKGHK HMDHM',
  'HNDHN HRVHR HTIHT HUNHU IDNID IRLIE ISRIL IMNIM INDIN IOTIO IRQIQ IRNIR ISLIS ITAIT JEYJE JAMJM',
  'JORJO JPNJP KENKE KGZKG KHMKH KIRKI COMKM KNAKN PRKKP KORKR KWTKW CYMKY KAZKZ LAOLA LBNLB LCALC',
  'LIELI LKALK LBRLR LSOLS LTULT LUXLU LVALV LBYLY MARMA MCOMC MDAMD MNEME MAFMF MDGMG MHLMH MKDMK',
  'MLIML MMRMM MNGMN MACMO MNPMP MTQMQ MRTMR MSRMS MLTMT MUSMU MDVMV MWIMW MEXMX MYSMY MOZMZ NAMNA',
  'NCLNC NERNE NFKNF NGANG NICNI NLDNL NORNO NPLNP NRUNR NIUNU NZLNZ OMNOM PANPA PERPE PYFPF PNGPG',
  'PHLPH PAKPK POLPL SPMPM PCNPN PRIPR PSEPS PRTPT PLWPW PRYPY QATQA REURE ROURO SRBRS RUSRU RWARW',
  'SAUSA SLBSB SYCSC SDNSD SWESE SGPSG SHNSH SVNSI SJMSJ SVKSK SLESL SMRSM SENSN SOMSO SURSR SSDSS',
  'STPST SLVSV SXMSX SYRSY SWZSZ TCATC TCDTD ATFTF TGOTG THATH TJKTJ TKLTK TLSTL TKMTM TUNTN TONTO',
  'TURTR TTOTT TUVTV TWNTW TZATZ UKRUA UGAUG UMIUM USAUS URYUY UZBUZ VATVA VCTVC VENVE VGBVG VIRVI',
  'VNMVN VUTVU WLFWF WSMWS XKKXK YEMYE MYTYT ZAFZA ZMBZM ZWEZW',
].join(' ')

const A3_TO_A2: ReadonlyMap<string, string> = new Map(A3_TO_A2_TABLE.split(' ').map((p) => [p.slice(0, 3), p.slice(3)]))

/** "USA" → "United States". Anything unknown (Google's "ZZZ", a code the table lacks) comes back
 *  as it came: a code read verbatim beats a dropped row. */
export function countryFromA3(code: string): string {
  const a2 = A3_TO_A2.get(code.toUpperCase())
  return a2 ? countryName(a2) : code
}
