/**
 * Generate `packages/site-bridge/src/social-icons.ts` — the brand mark for each platform
 * in `SOCIAL_PLATFORMS`.
 *
 * WHY GENERATED (the same reasoning as generate-bridge-tokens.ts): a hand-typed SVG path
 * is a mirror of somebody else's artwork, and a brand mark that is subtly wrong looks
 * worse than no mark at all. These come from `simple-icons`, whose icon data is CC0 —
 * a DEV dependency only, so nothing extra ships to a site or the editor at runtime.
 *
 * The generated file is COMMITTED and the package depends on nothing: a site importing
 * `@samfox1/site-bridge/social-icons` gets plain strings.
 *
 * Run: `npm run social-icons`. tests/social-icons.test.ts regenerates in memory and
 * diffs the committed file, so a platform added to the registry without regenerating
 * fails the build rather than shipping a platform with no mark.
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import * as si from 'simple-icons'
import { SOCIAL_PLATFORMS } from '../packages/site-bridge/src/social'

/** Registry slug → the simple-icons export name. Hand-mapped ONLY because the two
 *  vocabularies spell things differently ("apple music" vs `siApplemusic`); every entry
 *  is verified below, so a wrong name fails loudly instead of emitting an empty mark. */
const SI_EXPORT: Record<string, string> = {
  instagram: 'siInstagram',
  tiktok: 'siTiktok',
  youtube: 'siYoutube',
  spotify: 'siSpotify',
  'apple music': 'siApplemusic',
  soundcloud: 'siSoundcloud',
  bandcamp: 'siBandcamp',
  facebook: 'siFacebook',
  x: 'siX',
  threads: 'siThreads',
  substack: 'siSubstack',
  patreon: 'siPatreon',
  discord: 'siDiscord',
  twitch: 'siTwitch',
  deezer: 'siDeezer',
  tidal: 'siTidal',
}

type Icon = { title: string; hex: string; path: string }

export function buildSocialIcons(): string {
  const rows = SOCIAL_PLATFORMS.map((p) => {
    const exportName = SI_EXPORT[p.slug]
    if (!exportName) throw new Error(`No simple-icons mapping for "${p.slug}" — add one to SI_EXPORT.`)
    const icon = (si as unknown as Record<string, Icon>)[exportName]
    if (!icon?.path) throw new Error(`simple-icons has no "${exportName}" (for "${p.slug}").`)
    return `  ${JSON.stringify(p.slug)}: { path: ${JSON.stringify(icon.path)}, hex: ${JSON.stringify('#' + icon.hex)} },`
  })

  return `/**
 * GENERATED by scripts/generate-social-icons.ts — do not edit by hand.
 * Run \`npm run social-icons\` after changing SOCIAL_PLATFORMS.
 *
 * One brand mark per platform: a 24x24 SVG path and the brand's own colour. Icon data
 * from simple-icons (CC0), inlined so neither the editor nor a connected site takes a
 * runtime dependency on it.
 *
 * A site is free to ignore all of this and draw its own glyphs — the standard names the
 * platform (./social), it does not dictate a pixel. This exists so that a site which has
 * no opinion still gets a mark the fan recognizes.
 */

export type SocialIcon = {
  /** SVG path data, drawn in a \`0 0 24 24\` viewBox. */
  path: string
  /** The brand's own colour, for a site that wants it. Monochrome is the safer default:
   *  sixteen brand colours in one row rarely suits a site's design. */
  hex: string
}

export const SOCIAL_ICONS: Record<string, SocialIcon> = {
${rows.join('\n')}
}

/** The mark for a platform slug, or null for one the registry does not know (the
 *  "Something else" path) — which renders as a plain labelled link. */
export function socialIcon(slug: string): SocialIcon | null {
  return SOCIAL_ICONS[slug] ?? null
}
`
}

if (process.argv[1]?.endsWith('generate-social-icons.ts')) {
  const out = join(process.cwd(), 'packages/site-bridge/src/social-icons.ts')
  writeFileSync(out, buildSocialIcons())
  console.log(`wrote ${out} (${SOCIAL_PLATFORMS.length} marks)`)
}
