/**
 * Generate `src/lib/service-icons.ts` — the brand mark for each SERVICE connection
 * (Shopify, Bandsintown, Ticketmaster, Google Drive), for the dashboard's Connections page
 * and the editor. Sam, 2026-09-28: "Each connection should have an icon associated with it."
 *
 * The socials' marks live in the bridge (generate-social-icons.ts) because sites draw them;
 * services are never site buttons (Sam: Shopify "will interact with the merch buttons"), so
 * these stay in the dashboard. Same source and the same reason to generate: simple-icons,
 * CC0, a DEV dependency only; a hand-typed path is a mirror of somebody else's artwork.
 *
 * Run: `npm run service-icons`. tests/unit/manager-tools/connections/service-icons.test.ts
 * regenerates in memory and diffs the committed file.
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import * as si from 'simple-icons'

/** Connection key → the simple-icons export name. Every entry is checked below. */
const SI_EXPORT: Record<string, string> = {
  bandsintown: 'siBandsintown',
  drive: 'siGoogledrive',
  shopify: 'siShopify',
  ticketmaster: 'siTicketmaster',
}

type Icon = { title: string; hex: string; path: string }

export function buildServiceIcons(): string {
  const rows = Object.entries(SI_EXPORT).map(([key, exportName]) => {
    const icon = (si as unknown as Record<string, Icon>)[exportName]
    if (!icon?.path) throw new Error(`simple-icons has no "${exportName}" (for "${key}").`)
    return `  ${JSON.stringify(key)}: { path: ${JSON.stringify(icon.path)}, hex: ${JSON.stringify('#' + icon.hex)} },`
  })
  return `/**
 * GENERATED by scripts/generate-service-icons.ts — do not edit by hand.
 * Run \`npm run service-icons\` after adding a service connection.
 *
 * One brand mark per service connection, keyed by its connection key: a 24x24 SVG path and
 * the brand's own colour. Icon data from simple-icons (CC0), inlined so nothing ships the
 * package at runtime. Dashboard-only: services are never site buttons.
 */

export type ServiceIcon = {
  /** SVG path data, drawn in a \`0 0 24 24\` viewBox. */
  path: string
  /** The brand's own colour. The dashboard draws marks monochrome; kept for completeness. */
  hex: string
}

export const SERVICE_ICONS: Record<string, ServiceIcon> = {
${rows.join('\n')}
}
`
}

if (process.argv[1]?.endsWith('generate-service-icons.ts')) {
  const out = join(process.cwd(), 'src/lib/service-icons.ts')
  writeFileSync(out, buildServiceIcons())
  console.log(`service icons → ${out}`)
}
